import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rabbit Mart SE-GIU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="pure.png" />
       
      </Head>
      
         
                 
        
      <main className={styles.main}>

        

        <div className={styles.grid}>
        <form action="/send-data-here" method="post">
  <label for="email">Email:</label>
  <input
    type="text"
    id="email"
    name="email"
    required
    minlength="10"
    maxlength="20"
  />
  <label for="name">Name:</label>
  <input type="text" id="name" name="name" required />
  <button type="submit">Submit</button>
</form>

          <a href="https://anonymous-shipment-microservice.vercel.app/api/shipments" className={styles.card}>
            <h2>Track your Order &rarr;</h2>
            <p>Delivers all orders within 20 mins</p>
          </a>

          <a
            href="https://anonymous-shipment-microservice.vercel.app/api/shipments"
            className={styles.card}
          >
            <h2>Cancel Shipment &rarr;</h2>
            <p>Sorry for any inconvinence :(</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          
          
          
        </a>
        Copyright 2022
      </footer>
    </div>
  )
}